# Generated by Django 5.0.2 on 2024-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_alter_productcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='sub-categories/', verbose_name='фото подкатегории продукта'),
        ),
    ]
