# Generated by Django 5.0.2 on 2024-05-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_productcategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristic',
            options={'verbose_name': 'Название характеристики продукта', 'verbose_name_plural': 'Название характеристики продуктов'},
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.TextField(verbose_name='Характеристика продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='estore.product', verbose_name='Продукт')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.productcharacteristic', verbose_name='Название характеристики продукта')),
            ],
            options={
                'verbose_name': 'Характеристики продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
    ]
