# Generated by Django 5.0.2 on 2024-05-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_alter_productcharacteristic_options_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AddField(
            model_name='productreview',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_reviews', to='estore.profile', verbose_name='Пользователь'),
        ),
    ]
