# Generated by Django 5.0.2 on 2024-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=200, verbose_name='Адрес'),
        ),
    ]
