# Generated by Django 5.0.2 on 2024-05-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
