# Generated by Django 5.0.2 on 2024-05-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'cart')},
        ),
    ]
