# Generated by Django 5.0.2 on 2024-05-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0017_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
